### ISSUE TITLE
Limpieza de archivos y código en desuso

### ISSUE THREAD

**Issue by iyaki** [watefa1/Practica_Gabriel_G#1]
Veo una gran cantidad de archivos y código que no se está utilizando para hacer funcionar el sistema, pero que sigue commiteado. Por favor, eliminarlos.

Con revisar las carpetas `application/controllers` y `application/views` debería ser suficiente.

**Comment by watefa1** [comment]
Se quitaron las vistas y controladores que no se utilizan
